cat tests/01a-input.txt | ./Scheduler | diff tests/01a-output.txt -
cat tests/01b-input.txt | ./Scheduler | diff tests/01b-output.txt -
cat tests/02a-input.txt | ./Scheduler | diff tests/02a-output.txt -
cat tests/02b-input.txt | ./Scheduler | diff tests/02b-output.txt -
cat tests/03a-input.txt | ./Scheduler | diff tests/03a-output.txt -
cat tests/03b-input.txt | ./Scheduler | diff tests/03b-output.txt -
cat tests/04a-input.txt | ./Scheduler | diff tests/04a-output.txt -
cat tests/04b-input.txt | ./Scheduler | diff tests/04b-output.txt -
cat tests/05a-input.txt | ./Scheduler | diff tests/05a-output.txt -
cat tests/05b-input.txt | ./Scheduler | diff tests/05b-output.txt -
cat tests/06a-input.txt | ./Scheduler | diff tests/06a-output.txt -
cat tests/06b-input.txt | ./Scheduler | diff tests/06b-output.txt -
cat tests/07a-input.txt | ./Scheduler | diff tests/07a-output.txt -
cat tests/07b-input.txt | ./Scheduler | diff tests/07b-output.txt -
cat tests/08a-input.txt | ./Scheduler | diff tests/08a-output.txt -
cat tests/08b-input.txt | ./Scheduler | diff tests/08b-output.txt -
cat tests/09a-input.txt | ./Scheduler | diff tests/09a-output.txt -
cat tests/09b-input.txt | ./Scheduler | diff tests/09b-output.txt -
cat tests/10a-input.txt | ./Scheduler | diff tests/10a-output.txt -
cat tests/10b-input.txt | ./Scheduler | diff tests/10b-output.txt -
cat tests/11a-input.txt | ./Scheduler | diff tests/11a-output.txt -
cat tests/12a-input.txt | ./Scheduler | diff tests/12a-output.txt -